// Backward-compatibility barrel — re-exports from the new plugin system
export {
  loadPlugins,
  listTools,
  setToolEnabled,
  getSystemPrompt,
  parseToolCalls,
  executeTool,
  requestConfirmation,
  resolveConfirmation,
  cancelConfirmation,
  isToolGroupEnabled,
  getPluginStatuses,
  getPluginAuth,
  listPluginGroups,
  setPluginEnabled,
  updatePluginConfig,
  readPluginConfig,
  getTaskmasterPrompt,
} from '../tools/index.js';
